--=======ELIMINAR TABLAS ANTERIORES===
DROP TABLE IF EXISTS public.account_manager;
DROP TABLE IF EXISTS public.cliente;
DROP TABLE IF EXISTS public.persona;
DROP TABLE IF EXISTS public.product_owner;
DROP TABLE IF EXISTS public.proyecto;
DROP TABLE IF EXISTS public.tarea;
DROP TABLE IF EXISTS public.usuario_alerta;
DROP TABLE IF EXISTS usuario_alerta_param;
DROP TABLE IF EXISTS usuario_alerta_sup;

--=======TABLAS=================

-- Table: cliente-----
CREATE TABLE IF NOT EXISTS public.cliente
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre text COLLATE pg_catalog."default",
    CONSTRAINT cliente_pkey PRIMARY KEY (id)
);

-- Table: persona-----
CREATE TABLE IF NOT EXISTS public.persona
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    account_manager integer DEFAULT 0,
    project_owner integer DEFAULT 0,
    CONSTRAINT persona_pkey PRIMARY KEY (id)
);

-- Table: proyecto-----
CREATE TABLE IF NOT EXISTS public.proyecto
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre text COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default",
    fecha_entrega date,
    estado integer,
    cliente integer,
    project_owner integer,
    account_manager integer,
    plantilla text COLLATE pg_catalog."default",
    precio_venta money,
    x_prev_final date,
    x_fecha_hito_1 date,
    x_fecha_hito_2 date,
    x_fecha_hito_3 date,
    x_fecha_hito_4 date,
    x_fecha_hito_5 date,
    x_fecha_hito_6 date,
    x_importe_hito_1 money,
    x_importe_hito_2 money,
    x_importe_hito_3 money,
    x_importe_hito_4 money,
    x_importe_hito_5 money,
    x_importe_hito_6 money,
    x_horas_estimadas integer,
    CONSTRAINT proyecto_pkey PRIMARY KEY (id)
);

-- Table: tarea-----
CREATE TABLE IF NOT EXISTS public.tarea
(
    proyecto integer NOT NULL,
    persona integer NOT NULL,
    fecha_ini date,
    fecha_fin date,
    tiempo_estimado integer,
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    plantilla_id text COLLATE pg_catalog."default"
);

-- Table: ausencia-----
CREATE TABLE IF NOT EXISTS public.ausencia
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default",
    date_from date,
    date_to date,
    number_of_days integer,
    persona integer,
    hour_from integer,
    hour_to integer,
    request_unit text COLLATE pg_catalog."default",
    number_of_hours real
);

-- Table: calendario-----
CREATE TABLE IF NOT EXISTS public.calendario
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default",
    start_date date,
    stop_date date,
    allday integer
);

-- Table: usuario_alerta----
CREATE TABLE IF NOT EXISTS public.usuario_alerta
(
    email text COLLATE pg_catalog."default",
    horas_min integer,
    horas_max integer,
    name text COLLATE pg_catalog."default",
    alerta1 integer,
    alerta2 integer,
    id text COLLATE pg_catalog."default",
    alerta3 integer,
    extras integer DEFAULT 0
);

-- Table: usuario_alerta_param -----
CREATE TABLE IF NOT EXISTS public.usuario_alerta_param
(
    name text COLLATE pg_catalog."default",
    value1 text COLLATE pg_catalog."default",
    value2 text COLLATE pg_catalog."default"
);

-- Table: usuario_alerta_sup -----
CREATE TABLE IF NOT EXISTS public.usuario_alerta_sup
(
    name text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    id text COLLATE pg_catalog."default"
);

--Table: proyecto_estado----
CREATE TABLE IF NOT EXISTS public.proyecto_estado
(
    id integer,
    nombre text COLLATE pg_catalog."default"
);
INSERT INTO public.proyecto_estado(id, nombre)	VALUES (1, 'Borrador');
INSERT INTO public.proyecto_estado(id, nombre)	VALUES (2, 'Planificación completada');
INSERT INTO public.proyecto_estado(id, nombre)	VALUES (3, 'Cerrado');
INSERT INTO public.proyecto_estado(id, nombre)	VALUES (100, 'Ganado');


--Insertar en la tabla SELECT name, value1, value2 	FROM public.usuario_alerta_param;
INSERT INTO public.usuario_alerta_param(name,value1,value2) 
VALUES ('frecuencia_sup','mensual', 'ultima_sem');
INSERT INTO public.usuario_alerta_param(name,value1,value2) 
VALUES ('frecuencia_usuario','mensual', 'ultima_dia')	
